// generated by generate_yaml.py

//
// Enums first
//

static const struct YamlIdStr enum_MixSources[] = {
  {  MIXSRC_NONE, "NONE"  },
  {  MIXSRC_Rud, "Rud"  },
  {  MIXSRC_Ele, "Ele"  },
  {  MIXSRC_Thr, "Thr"  },
  {  MIXSRC_Ail, "Ail"  },
  {  MIXSRC_S1, "S1"  },
  {  MIXSRC_6POS, "6POS"  },
  {  MIXSRC_S2, "S2"  },
  {  0, NULL  }
};

//
// Structs last
//

static const struct YamlNode struct_unsigned_8[] = {
  YAML_UNSIGNED( "val", 8 ),
  YAML_END
};
static const struct YamlNode struct_ModelHeader[] = {
  YAML_STRING("name", 10),
  YAML_ARRAY("modelId", 8, 2, struct_unsigned_8, NULL),
  YAML_END
};
static const struct YamlNode struct_CurveRef[] = {
  YAML_UNSIGNED( "type", 8 ),
  YAML_SIGNED( "value", 8 ),
  YAML_END
};
static const struct YamlNode struct_MixData[] = {
  YAML_IDX,
  YAML_SIGNED( "weight", 11 ),
  YAML_UNSIGNED( "destCh", 5 ),
  YAML_ENUM("srcRaw", 10, enum_MixSources),
  YAML_UNSIGNED( "carryTrim", 1 ),
  YAML_UNSIGNED( "mixWarn", 2 ),
  YAML_UNSIGNED( "mltpx", 2 ),
  YAML_UNSIGNED( "spare", 1 ),
  YAML_SIGNED( "offset", 14 ),
  YAML_SIGNED( "swtch", 9 ),
  YAML_UNSIGNED( "flightModes", 9 ),
  YAML_STRUCT("curve", 16, struct_CurveRef, NULL),
  YAML_UNSIGNED( "delayUp", 8 ),
  YAML_UNSIGNED( "delayDown", 8 ),
  YAML_UNSIGNED( "speedUp", 8 ),
  YAML_UNSIGNED( "speedDown", 8 ),
  YAML_STRING("name", 6),
  YAML_END
};
static const struct YamlNode struct_anonymous_1[] = {
  YAML_STRING("name", 6),
  YAML_END
};
static const struct YamlNode struct_anonymous_2[] = {
  YAML_SIGNED( "val", 16 ),
  YAML_UNSIGNED( "mode", 8 ),
  YAML_UNSIGNED( "param", 8 ),
  YAML_SIGNED( "spare", 16 ),
  YAML_END
};
static const struct YamlNode struct_anonymous_3[] = {
  YAML_SIGNED( "val1", 32 ),
  YAML_SIGNED( "val2", 16 ),
  YAML_END
};
static const struct YamlNode union_anonymous_0_elmts[] = {
  YAML_STRUCT("play", 48, struct_anonymous_1, is_custFnData_play),
  YAML_STRUCT("all", 48, struct_anonymous_2, is_custFnData_all),
  YAML_STRUCT("clear", 48, struct_anonymous_3, is_custFnData_clear),
  YAML_END
};
static const struct YamlNode struct_CustomFunctionData[] = {
  YAML_IDX,
  YAML_SIGNED( "swtch", 9 ),
  YAML_UNSIGNED( "func", 7 ),
  YAML_UNION("", 48, union_anonymous_0_elmts, NULL),
  YAML_UNSIGNED( "active", 8 ),
  YAML_END
};
static const struct YamlNode struct_string_256[] = {
  YAML_IDX,
  YAML_STRING("val", 32),
  YAML_END
};
static const struct YamlNode struct_ExpoData[] = {
  YAML_UNSIGNED( "mode", 2 ),
  YAML_UNSIGNED( "scale", 14 ),
  YAML_UNSIGNED( "srcRaw", 10 ),
  YAML_SIGNED( "carryTrim", 6 ),
  YAML_UNSIGNED( "chn", 5 ),
  YAML_SIGNED( "swtch", 9 ),
  YAML_UNSIGNED( "flightModes", 9 ),
  YAML_SIGNED( "weight", 8 ),
  YAML_SIGNED( "spare", 1 ),
  YAML_STRING("name", 6),
  YAML_SIGNED( "offset", 8 ),
  YAML_STRUCT("curve", 16, struct_CurveRef, NULL),
  YAML_END
};
static const struct YamlNode union_ScriptDataInput_elmts[] = {
  YAML_SIGNED( "value", 16 ),
  YAML_UNSIGNED( "source", 16 ),
  YAML_END
};
static const struct YamlNode union_ScriptDataInput[] = {
  YAML_UNION("", 16, union_ScriptDataInput_elmts, NULL),
  YAML_END
};
static const struct YamlNode struct_ScriptData[] = {
  YAML_STRING("file", 6),
  YAML_STRING("name", 6),
  YAML_ARRAY("inputs", 16, 6, union_ScriptDataInput, NULL),
  YAML_END
};
static const struct YamlNode struct_Model[] = {
  YAML_STRUCT("header", 96, struct_ModelHeader, NULL),
  YAML_ARRAY("mixData", 160, 4, struct_MixData, NULL),
  YAML_ARRAY("customFn", 72, 8, struct_CustomFunctionData, NULL),
  YAML_ARRAY("inputNames", 256, 4, struct_string_256, NULL),
  YAML_ARRAY("expoData", 136, 8, struct_ExpoData, NULL),
  YAML_ARRAY("scriptsData", 192, 9, struct_ScriptData, NULL),
  YAML_END
};

#define MAX_MODEL_STR_LEN 11
